### ISSUE TITLE
Unable to generate Stark Private Key on Windows machine on Go 1.18

### ISSUE THREAD

**Issue by sumitbhowmick** [immutable/imx-core-sdk-golang#93] opened 2022-11-14 04:03 UTC
In IMX examples common package, stark key generation fails due to following exception
`starkPrivateKey, err = stark.GenerateKey()`

ERRO[0010] panic: error in Generating Stark Private Key: open github.com\immutable\imx-core-sdk-golang@v0.2.1\imx\signers\stark/pedersen_params.json: The system cannot find the path specified.

Looks like a path syntax issue or missing files.
If we hardcode the path, eliminating the need for determining path, then it works. However, that is not a practical solution.
Request to solve this.

**Comment by suluvai** [comment] 2022-11-17 02:57
@sumitbhowmick I have tested this and not able to reproduce the issue, it worked fine.

Tested it using the unit test and also as a imported module in a sample application with the following code. It worked in both cases well.

`package main

import (
	"log"

	"github.com/immutable/imx-core-sdk-golang/imx/signers/stark"
)

func main() {
	sPrivateKey, err := stark.GenerateKey()
	if err != nil {
		log.Fatal(err)
	}
	log.Println(sPrivateKey)
}`

**Comment by sumitbhowmick** [comment] 2022-11-17 03:52
@suluvai This works fine when it gets executed independently. 
I'm developing a k6 extension where this sdk is called. K6 runs on goja VM.
https://k6.io/docs/extensions/explanations/go-js-bridge/ 
When this code gets executed on goja VM, this error occurs.

This possibly occurs due to the fact that absolute path is system dependent. On Windows, with goja vm, following path pattern is expected.
pedersenParamsFilePath := "C:\\repo\\k6\\imx-sdk-golang-k6\\imx\\signers\\stark\\pedersen_params.json"
sc, err := caigo.SC(caigo.WithConstants(pedersenParamsFilePath))

SDK Root directory: C:\\repo\\k6\\imx-sdk-golang-k6

So, following options may be evaluated:
1. If some package can accept relative path and pass it to required functions & packages.
2. Option to specify path in environment variable.
3. Use of path determination package which is compatible with goja vm

**Comment by suluvai** [comment] 2022-11-23 07:09
@sumitbhowmick please check if the fix in the branch works for you on goja VM?
https://github.com/immutable/imx-core-sdk-golang/tree/ISSUE-93

**Comment by sumitbhowmick** [comment] 2022-11-23 07:52
No, I still get the same error.

ERRO[0005] a panic occurred during JS execution: error in Generating Stark Private Key: open github.com\sumitbhowmick\imx-core-sdk-golang@v0.0.0-00010101000000-000000000000\imx\signers\stark\pedersen_params.json: The system cannot find the path specified.

**Comment by suluvai** [comment] 2022-11-24 05:48
Why is that not converted to a full path? Does it need to be double slash to work on goja vm?

**Comment by sumitbhowmick** [comment] 2022-11-24 06:09
Yeah, it need to be double dash, at least for absolute path.
For me, absolute path like this is working for me now.
C:\\repo\\k6\\imx-sdk-golang-k6\\imx\\signers\\stark\\pedersen_params.json
I tried relative path, but it didn't work.

**Comment by suluvai** [comment] 2022-11-24 06:39
Function `currentDirname` defined here https://github.com/immutable/imx-core-sdk-golang/blob/c52cd329df61ccfaf92c5f737aa6e87f4bf140d7/imx/signers/stark/factory.go#L84 should obtain the absolute path, but the error log suggests that you are not getting the absolute path. Do you mind joining for a quick chat?

**Comment by sumitbhowmick** [comment] 2022-11-24 07:48
Sure thing. Jesse has my contacts. Feel free to get in touch.

**Comment by suluvai** [comment] 2022-11-30 10:41
Addressed by https://github.com/immutable/imx-core-sdk-golang/pull/101

**Closed** 2022-12-06 03:50 UTC
